services:
  db:
    image: mysql:latest
    container_name: oop_demo_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: library
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: